### PR TITLE
Update execution_handler.py

### PR DESCRIPTION
**Pull request by femtotrader**
Remove unused datetime import

### CODE REVIEW

**Comment by mhallsmoore** [comment]
I didn't realise the build was considered "failed" if it doesn't pass PEP8! Although, I guess that's pretty useful.

**Comment by femtotrader** [comment]
Yes the build was considered "failed" if it doesn't pass PEP8 because fixing flake8 error help to keep a clean code. but PEP8 checking is done after unit tests so you can see in Travis builds if unit tests are passing correctly because I think it's more important to have code that pass unit test than code that pass both...
but to be merged code should pass both.

**Comment by ryankennedyio** [comment]
I find linting to be very helpful in dynamically typed languages - agree RE PEP8 compliance.

@femtotrader is there an easy a way to simulate the travis-CI build locally, before we push code up to branches here?

**Comment by mhallsmoore** [comment]
Agreed. The project will attract more good software developers if we can keep code clean and unit tests passing.

**Comment by femtotrader** [comment]
@ryankennedyio simulate the Travis-CI build locally ? I never do this...
Travis rely on Docker containers.

I know that some Python dev use tox http://tox.readthedocs.io/en/latest/ to manage test, deployment...

You can also urge git to run some command lines before commit (run tests, PEP8...)

but I personaly don't do it and rely heavily on Travis.

I also don't use virtualenv (I use conda)

**Pull request merged**
