### PR TITLE
Arithmetic optimisation

### PR DESCRIPTION
**Pull request by ryankennedyio**
NOT YET READY FOR MERGE -- Need to fix for several tests.

Just want a review of style. @mhallsmoore @femtotrader. Very close to being done.
Apologies for delay -- workload leading into product launch got a bit ridiculous.

Supporting multiple types (int, float, Decimal) internally is going to add a lot of complexity and overhead. I prefer the simple idea of a one-time parse for numbers going _into_ qstrader, and a one-time parse for numbers coming _out_ of qstrader. If the input numbers are already `int`, we shouldn't parse them. As such, the user should probably explicitly pass numbers in as floats.

Just mentioning that.. Need to update the price handlers to force all data from the CSVs to be float.

Note that this is only relevant for price too, volume, etc needs no parsing. Because of this, I've named the parser a simple `PriceParser`, to remove any ambiguity as to when & how it should be used.

### CODE REVIEW

**Comment by femtotrader** [comment]
multipledispatch need to be add as dependency
There is also a lot of flake8 errors (often missing space before and after `=`)
some tests are broken but I like some ideas as it leads to simpler code.

**Comment by ryankennedyio** [comment]
Thanks @femtotrader. Going through and fixing tests now.

I have one minor issue where the expected results of the buy and hold backtest are off by 1 cent at the final value. I have a hunch that this could be due to floating point precision error when I originally multiply the decimal out of the numbers received in the PriceHandler. Will fix that after linting is fixed and the rest of the tests run correctly.

The `examples/test_examples.py` tests run in 0.691s now, as opposed to around ~7.2s.
Largely result of not using Series in Statistics anymore until the last possible moment.

**Comment by ryankennedyio** [comment]
Actually, also on the note of precision error -- has anyone checked out the CSV files in `data` lately .... ? They do look a bit funny (off by thousandth of a cent ish). Might be worth fetching them from source again.

**Comment by ryankennedyio** [comment]
Now passing all tests except for one. Will deal with that tomorrow morning, then quickly run through linting. Will see if I can find out what's causing my 1 cent error too, and re-enable that test.

Think something is definitely up with the source CSV file accuracy. Tests have been refactored to accommodate at some point but I think they're erroneous. Won't actually make a technical difference, just not pretty.

**Comment by ryankennedyio** [comment]
Ready to rock @mhallsmoore .

Will spend the rest of the day working on this with personal strategies, so won't play with the precision error. I've marked those with #TODO for now.

**Comment by mhallsmoore** [comment]
Great work! Thanks @ryankennedyio.

**Pull request merged**
