### PR TITLE
Ibpricehandler

### PR DESCRIPTION
**Pull request by ryankennedyio**
Looks like a bunch more changes are showing in this diff than there should be. Probably because of merging Master back into it. Anyway.
- Created `ib.py` as a wrapper over swigibpy's EWrapper class. This will have more extensive logging, alerts, exception handling, etc.
- Try to throw exceptions properly in `ib.py` -- swigibpy just prints them by default. Not yet working.... (...?????)
- Created `test_ib.py`
- Started working on IB price handler
- Started working on IB price handler test.

Discussion point for future; should we be creating a new connection to IB for every class that needs it? E.g. IBExecutionHandler, IBPortfolio, IBPriceHandler would all, in future, call their own IB setup methods. They would each technically be a 'client' of IB. This seems to be standard practice ... is that right?

### CODE REVIEW

**Comment by femtotrader** [comment]
I also think we will need `IBExecutionHandler`, `IBPortfolio` in addition to `IBPriceHandler`
maybe an additional object to keep connection details will be required.

**Comment by mhallsmoore** [comment]
I think we need to add swigibpy to the requirements.txt and then the Travis builds should pass.

@ryankennedyio - As to your point about separate client interactions with IB, I think we should do this, as larger architectures may want to run separate parts of the code on different systems and it's somewhat cleaner to have multiple client IDs.

**Comment by ryankennedyio** [comment]
@mhallsmoore 

Swigibpy is only available as 0.4.1 as a pip install. Have asked @Komnomnomnom if V0.5.0 can be released. There's a fair bit of difference between the two versions.

Hopefully we don't need to include 0.5.0 as part of our setup.py script, but if 0.5.0 can't get released soon we'll just do that.

**Comment by ryankennedyio** [comment]
A little further work. Feedback welcome. 

Rather than maintain a `mkt_data_queue` in `ib.py`, I think I should just pass in the PriceHandler's reference of the `events_queue`, which tidies things up a little better.

**Comment by femtotrader** [comment]
I think a queue in price handler is necessary.
I didn't use one in IG price handler
see https://github.com/mhallsmoore/qstrader/blob/master/qstrader/price_handler/ig.py#L38
but that's definitely necessary if we don't want to loose price events in a multithreading context.

**Comment by ryankennedyio** [comment]
Should we use `multiprocess.Queue()`? I did to start with, except went back to the single-threaded one for now. Further, if we have multiple IB clients, it will be important to ensure that only the PriceHandler 'client' does any market data requests, else we'll lose stuff.

I am maintaining a market data queue in ib.py, so the PriceHandler simply acts as an interface between ib.py and the rest of qstrader. Implementation is a bit dirty so I'll clean up tomorrow.

**Comment by mhallsmoore** [comment]
I'll have a solid look at this upon return from vacation (Sep 1st/2nd) and we can see how the architecture is looking then.

**Comment by ryankennedyio** [comment]
OK, now pulls in historical data from as many tickers as you want (well, I have tried with 5...)

Main todos:
* No locking mechanism that waits for IB hist data to be populated before backtest begins. Have just done a nasty time.sleep(5) when working on it.
* Thrown exceptions in `ib.py` callbacks don't propagate back to the main thread.
* Think about contract base currency?
* Bar size is presumed to be 5 minutes
* No real time streaming yet
* No mock IB class for unit testing (eurgh)

**Comment by ryankennedyio** [comment]
* Added locking mechanism, now waits for all the data you request to be available before starting.
* Dynamic bar sizes (can do whatever IB allows)

Still no realtime streams, and our returns look a little awkward now .... 
screen shot 2016-09-06 at 7 15 47 pm


Also, IB only gives like 10 days of minute data? Very lame.

**Comment by mhallsmoore** [comment]
This is great! 

Once the Travis builds are working, we can sort out integrating this into the codebase.

We also need to think about creating a better interpolation mechanism for Seaborn/Matplotlib. I think it will simply involve adding an extra value prior to a large spike up or down.

**Comment by ryankennedyio** [comment]
Looks like we will also have to build swigibpy V0.5.0 as part of our setup.py for the time being too.

Will be a good chunk of work having the IB things mocked for Travis. Shouldn't be overly complex, just tedious. I think once that, and realtime streaming, I think we can get started on IB execution handler & IB portfolio (load positions, etc)

**Pull request closed without merging**
