### PR TITLE
Statistics

### PR DESCRIPTION
**Pull request by ryankennedyio**
* Statistics class now works entirely in memory.
* Removed references to equity_file in backtests.
* Equity, drawdown and period returns are calculated on-the-go.
* Created convenience "get_results()" method.
* Sharpe calculation against 1% risk-free return (yay negative rates), pulled from your article in '13.
* Max drawdown, max drawdown percent both calculated in get_results() too.
* Equity, equity returns and drawdown have tests.

**No tests yet for:**
sharpe, max DD or max DD %

### CODE REVIEW

**Comment by mhallsmoore** [comment]
Ryan, thanks for this - just to check, before I make an inclusion, have you "hardcoded" the 1% interest rate in the SR? I suggest we make that a configurable parameter, perhaps defaulting to zero.

**Comment by ryankennedyio** [comment]
Great point, will fix that up.

Would you have any preferences on the timeframes as well ? I know SR is meant to be reflective of the time-periods being traded on (daily vs hourly, etc) but I'm unsure if that's normally included "in practice"

**Comment by mhallsmoore** [comment]
Ryan,

Apologies for not merging this in yet. I've got a few merge conflicts that need resolution, so I'll attempt to do so. Once they're fixed and tested I'll push up a proper version.

Cheers,

Mike.

**Comment by ryankennedyio** [comment]
Hey Mike,

Let me deal with it and tag you here when I've done that -- just back from holiday now so have some more time. Will sort out the configurable SR benchmark % at the same time.

Ryan

**Comment by mhallsmoore** [comment]
Hi Ryan,

Great - let me know how you get on with the merge conflicts!

Cheers,

Mike.

**Comment by ryankennedyio** [comment]
@mhallsmoore sorted now.

SR Benchmark isn't "really" configurable in the sense that you can't really call the method or set the benchmark before running the backtest from the simple "working" files.

I have resolved this in a "future" commit. I'm a bit split out from your master at the moment, so just working now to add some changes to another branch and will PR that.

**Comment by ryankennedyio** [comment]
@mhallsmoore Conflicts from the new upstream/master are resolved :)

**Pull request merged**
