### PR TITLE
Price Iterator, Pandas BarEvent TickEvent Iterator (for DataFrame and Panel) 

### LINKED ISSUE #58: DataFrame / Panel price handler
According discussion https://github.com/mhallsmoore/qstrader/pull/53

Maybe a more general price handler should be done
This price handler could have 
 - a DataFrame as input (when a backtest for only one ticker is necessary)
 - a Panel as input (when a backtest with several tickers is given)

Index will be Time

Depending of columns names it could be either 
- a tick price handler (need at least a column `Price` or `Bid`/`Ask` and optionally `Volume`(s))
- a bar price handler (need at least columns named `Open` `High` `Low` `Close`)

```python
import pandas as pd
import pandas_datareader.data as web
import datetime
import requests_cache


expire_after = datetime.timedelta(days=3)
session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)
panel = web.DataReader(["GOOG", "IBM"], "yahoo", session=session)
```

Panel looks like:

```
<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1630 (major_axis) x 2 (minor_axis)
Items axis: Open to Adj Close
Major_axis axis: 2010-01-04 00:00:00 to 2016-06-23 00:00:00
Minor_axis axis: GOOG to IBM
```

```
def data_from_dataframe(df):
    for (dt, row) in df.iterrows():
        yield(dt, row)

def data_from_panel(panel):
    for dt, data in panel.transpose(1,0,2).iteritems():
        for (ticker, bar) in data.iteritems():
            yield(dt, ticker, bar)

ticker = "GOOG"
df = panel[:,:,ticker]
for (dt, bar) in data_from_dataframe(df):
    print(dt, ticker, bar)

for (dt, ticker, bar) in data_from_panel(panel):
    print(dt, ticker, bar)

```

### PR DESCRIPTION
**Pull request by femtotrader**
and **Generic Price Handler**

This is a quite big PR.

Closes #58
Should also help #101 

Because it's now much easier to create your own price data source for backtesting

It separates 2 roles :
 - Price Event Iterator
 - Price Handler (put `TickEvent` or `BarEvent` to event queue)

A price event iterator simply need to return a `TickEvent` or a `BarEvent` at `next` call.
Price Handler can be generic - a generic price handler just need a price event iterator (inherited from `AbstractTickEventIterator` or `AbstractBarEventIterator`)

4 new price event iterators are given
- Input : Pandas DataFrame with OLCV columns and datetime as index for ONE ticker - output `BarEvent`
- Input : Pandas Panel with OLCV as items axis, datetime as major_axis axis and tickers as minor_axis axis - output `BarEvent`
- Input : Pandas DataFrame with Bid/Ask columns and datetime as index for ONE ticker (so for several tickers) - output `BarEvent`
- Input : Pandas Panel with Bid/Ask as items axis, datetime as major_axis axis and tickers as minor_axis axis (so for several tickers) - output `BarEvent`

These iterators are just examples, there is no need to put data into Pandas... iterators are the way to follow.

One big advantage of this is that anyone can easily test his price iterator by just doing

    price_event_iterator = MyNewIterator()
    for event in price_event_iterator:
        print(event)

### CODE REVIEW

**Comment by femtotrader** [comment]
Closes also https://github.com/mhallsmoore/qstrader/issues/104

**Comment by femtotrader** [comment]
Back to a more acceptable code coverage.
PEP8 fixed.

In a next PR I think we should split data directory into `data/bar` and `data/tick`
and remove pandas_datareader and just use "raw" CSV data in `examples/pandas/...`.

I also think that we should use "round" date range for data

SP500TR for example is from 2010-01-04 to 2016-06-22
maybe we should only have data up to  2015-12-31.

**Comment by ryankennedyio** [comment]
This abstraction is nice!

Out of interest, have you done any speed comparisons for tick data with this? Particularly with backtests we'll notice if anything adds much more time. Though at the moment the majority of the time is currently spent by Pandas trying to "guess" the format of our Dates. Some low-hanging optimisation fruit there for sure.

Nagging point, but can we explain this (motiviation for it, and run through example) in docs (or a Wiki for now @mhallsmoore ) ?? This does add a boatload of "up front" complexity that people have to come to terms with when looking at the system for the first time. Yes, it is very clean and modular, but still daunting!

**Comment by femtotrader** [comment]
You can have a look at `nose-timer` results in CI... it doesn't seems to reduce speed.

Running examples show similar bar/tick speed.

About " Pandas trying to "guess" the format ", we can pass datetime format manually like

```python
df['Date'] = pd.to_datetime(df['Date'], format='%d%m%Y %H:%M:%S.%f')
```

I really think it's important to merge this because it will become possible to build custom price data feed more easily. We will just need to explain how to make an iterator!

**Comment by mhallsmoore** [comment]
I'm happy to merge this, but before I do I think we're going to need some documentation. Perhaps you guys are probably better placed to do so, having worked on the feature? Otherwise I can take a look at it over the next week or so and write up some instructions.

We should definitely be having some conversations around OOP complexity and ease of use trade-offs. It would be a shame if the project eventually had so much abstraction that it became unusable without a lot of upfront learning.

What do you guys think?

**Comment by femtotrader** [comment]
I'm not native english speaker so writing doc is not my best skill ;-)

Anyway maybe this PR is not the best way to perform the task of being able to use Pandas DataFrame and Pandas Panel as price/volume provider.
Maybe the idea to separate price iterator and price handler is over-engineered... in such a case we should merge the two roles and use multiple inheritance.

So this abstraction will be out of "users" eyes.

**Comment by ryankennedyio** [comment]
@mhallsmoore complexity is going to be a tricky thing to manage. Especially if it should cater for insto-level too.

I believe that the system should eventually be "out-of-the-box" able to cater for people to get started and running a backtest on Yahoo data with their own simple strategy within an hour or two.

But at the same time, it should be modular enough that if someone wants to start poking around some of the extra components to modify, they should be able to dive in without knowing too much about the other moving parts.

I feel like we're sitting on a pretty good mix at the moment? Hard to know without new people's feedback.

It might be a good idea for us to have a public Gitter where we can carry out these discussions, as well as get feedback from newer users ??? We're having a tendency to clog up issues and PR's with longer term discussion which, don't get me wrong, is really great, but might be best suited for a chatroom? Once things are more clear after chatting, we can bring them in as issues to work on properly here.

**Comment by ryankennedyio** [comment]
@mhallsmoore on the last point, could you set up a gitter.im room for qstrader? Will be useful to chat about roadmap/higher level things over there.

**Comment by nwillemse** [comment]
I know some developers love slack to communicate over projects. It has great integration with github.

https://github.com/integrations/slack

**Comment by mhallsmoore** [comment]
I've just setup a new QSTrader Slack account and have integrated the QSTrader with Github as per your link. I'm just going to test it works, then I'll make another Github Issue with email address invites.

**Pull request merged**
