### PR TITLE
Open short position has incorrect market_value, unrealized and realized pnl

### PR DESCRIPTION
**Pull request by nwillemse**
When short position is open, the calculation of market_value does not look correct.  That affects the calculation of unrealized and realized pnl and subsequently portfolio equity.  I created a test to show the issue.

### CODE REVIEW

**Comment by ryankennedyio** [comment]
@nwillemse could I argue that `realised_pnl` should be `0 - commission` when a position is opened?

https://github.com/mhallsmoore/qstrader/pull/137/files#diff-486eebb24e5b61967fc2f258c52152c1R157

**Comment by ryankennedyio** [comment]
OK this fixes, except the `realised_pnl` tests fail. If I comment them out, rest of the test suite runs perfectly. 

@nwillemse could you change the def of update_market_value to the following, inside `position.py` ? I can't be bothered going through the PR dance with your tests not yet merged in :)

```
    def update_market_value(self, bid, ask):
        """
        The market value is tricky to calculate as we only have
        access to the top of the order book through Interactive
        Brokers, which means that the true redemption price is
        unknown until executed.

        However, it can be estimated via the mid-price of the
        bid-ask spread. Once the market value is calculated it
        allows calculation of the unrealised and realised profit
        and loss of any transactions.
        """
        midpoint = (bid + ask) // 2
        self.market_value = self.quantity * midpoint
        if self.net < 0:
            self.market_value = self.market_value * -1
        self.unrealised_pnl = self.market_value - self.cost_basis
        self.realised_pnl = self.market_value + self.net_incl_comm
```


@mhallsmoore could you have a look at `realised_pnl` ? I am unsure if this is only meant to be calculated after transactions have taken place. Also I am unsure if the above behaviour is desired (negative market value on opening a short). Best a question for Mike, but the above code is a simple fix.

**Comment by nwillemse** [comment]
Hi @ryankennedyio yes I can update it.  I did a test yesterday in IB paper account:

1) Created a short STK position (-100 shares of SPY)
2) The realised pnl is zero and the unrealized pnl gets updated with market events
3) Buy back 50 shares of SPY
4) Realised pnl is now updated
5) Close the trade and unrealised is zero and realised pnl is updated

Of course this is different when we are dealing with futures which is mark-to-market every day

**Comment by nwillemse** [comment]
Actually I think `realised_pnl` should not be updated on every `update_market_value event`. It only changes when a long position has a sell transaction and a short position has a buy transaction...

**Comment by ryankennedyio** [comment]
I think I agree with you @nwillemse  -- realised_pnl should only be updated within the `transact_shares()` method?

Might modify some tests and ensure that behaviour happens. Sounds OK @mhallsmoore ?

**Comment by mhallsmoore** [comment]
Hi guys, I'm just on vacation at the moment, but will be back the week of Sep 1st/2nd.

This looks fine to me, so I'll merge it in now, but I'll have a proper check when I'm back home!

**Pull request merged**
