### PR TITLE
Position fixes

### PR DESCRIPTION
**Pull request by femtotrader**
Should replace https://github.com/mhallsmoore/qstrader/pull/33
and closes https://github.com/mhallsmoore/qstrader/issues/28

### CODE REVIEW

**Comment by femtotrader** [comment]
This PR now pass tests/test_position.py but it breaks other tests...
@mhallsmoore could you have a look ?

**Comment by femtotrader** [comment]
Pinging also @trb5me

**Comment by trb5me** [comment]
From what I remember, `tests/test_position.py` only tests certain equalities _after_ a round trip was terminated. I remember suspecting a certain quantity was incorrect _while_ a position was open.

**Comment by mhallsmoore** [comment]
I'll take a look at why it's failing and resolve. I'll be back home tomorrow evening, so should be able to look at it on Friday.

**Comment by mhallsmoore** [comment]
I'm going to close this as I've now added these Position fixes into another pull request (https://github.com/mhallsmoore/qstrader/pull/177) due to the underlying changes in the codebase.

**Pull request closed without merging**
