### PR TITLE
Position fixes

### PR DESCRIPTION
**Pull request by trb5me**

### CODE REVIEW

**Comment by femtotrader** [comment]
Did you close this PR because it's fixed now or because there is too much change since you did it and it need rebase from master ?

**Comment by mhallsmoore** [comment]
I'll re-open it and see what the unit tests say. I think it wasn't possible to merge, but we'll see. It's possible it might need to be rebased.

Thanks for making the changes though!

**Comment by mhallsmoore** [comment]
Indeed, it says there is a merge conflict. Are you able to rebase from master and add it in? There's been a lot of changes since then...!

**Comment by femtotrader** [comment]
It may be worth (and easier) to create an other PR and add manually changes.

**Comment by femtotrader** [comment]
because this PR only change 2 files

**Comment by femtotrader** [comment]
This PR can be closed because there is now
https://github.com/mhallsmoore/qstrader/issues/84

**Comment by trb5me** [comment]
The second one. I closed it because it needed to be rebased. I checked back a while after the PR and there was so much that had been changed.

**Comment by trb5me** [comment]
This replaces #84 since it doesn't rely on Decimal anymore. And it replaces #33. 

I was following [this](https://www.interactivebrokers.com/en/software/tws/usersguidebook/realtimeactivitymonitoring/profit_and_loss.htm).

It still breaks a few more tests that I haven't looked into yet. I'm a little worried because this is one of the most elemental modules.

**Comment by mhallsmoore** [comment]
I'm going to close this as I've now added these Position fixes into another pull request (https://github.com/mhallsmoore/qstrader/pull/177) due to the underlying changes in the codebase.

**Pull request closed without merging**
