### PR TITLE
Update settings.py

### PR DESCRIPTION
**Pull request by ryankennedyio**
Not sure if this was a mistake originally?

### CODE REVIEW

**Comment by femtotrader** [comment]
Yes it was a mistake...
but settings.py is much easier to use now.
and is part of this https://github.com/mhallsmoore/qstrader/pull/57/files

see https://github.com/qstraders/qstrader/blob/bffc1a15f5634b49848c6aa741495646044138b0/qstrader/settings.py

`expanduser` is done when a directory is necessary (not in settings)

**Comment by ryankennedyio** [comment]
Sorry @femtotrader -- didn't realise there was a PR existing for it.

**Comment by femtotrader** [comment]
No problem @ryankennedyio 
There was so many PR ;-)
but we are now on the good track.
Thanks @mhallsmoore

**Comment by mhallsmoore** [comment]
Yeah, I merged a lot this morning, it's been a busy week!

I'll have a lot more time next week, so I'm looking forward to start working on some more sophisticated example strategies.

**Pull request closed without merging**
