### PR TITLE
Tearsheet Statistics Class

### PR DESCRIPTION
**Pull request by nwillemse**
First version of the `Tearsheet` statistics class with an example mac_backtest_tearsheet.py.  Currently only bars supported until we can figure out a common interface to `Bars` and `Ticks` (i.e. add `get_last_price()` method to both)

Missing some trade statistics because we don't have position entry/exit dates, # bars in trade, etc.

Comments?

Closes https://github.com/mhallsmoore/qstrader/issues/90

### CODE REVIEW

**Comment by femtotrader** [comment]
To improve code coverage you might add a test which run your example
https://github.com/mhallsmoore/qstrader/blob/master/examples/test_examples.py

**Comment by nwillemse** [comment]
@femtotrader Ok I will add it

**Comment by ryankennedyio** [comment]
@nwillemse looks like a Python3 issue with `PriceParser.display()`. Do you have a PR waiting that should fix that @femtotrader ?

**Comment by femtotrader** [comment]
I don't understand why in Python 2 we are having legacy int, and in Python 3 we have Numpy int64

I see two differents ideas:


1) have same type for both version
2) overcome this issue by improving `price_parser`

I would try something like

https://github.com/mhallsmoore/qstrader/pull/100

```python
    int_t = (*six.integer_types, np.int64)

    @staticmethod
    @dispatch(int_t)
    def parse(x):  # flake8: noqa
        return x
```

**Comment by femtotrader** [comment]
@staticmethod
    @dispatch(int_t)
    def display(x):  # flake8: noqa
        return round(x / PriceParser.PRICE_MULTIPLIER, 2)

in fact

**Comment by ryankennedyio** [comment]
@nwillemse -- is there any chance you could try to add Femto's suggestion to your own repo (make a branch *from* this branch, and add the suggested change to that branch)?

If that works, we know #100 needs to be merged in, in order for this PR to be merged in. I think #100 should probably get merged in for the sake of best practice anyway @mhallsmoore, as the suggested library was built for handling these 2-3.

**Comment by mhallsmoore** [comment]
#100 has now been merged, so @nwillemse should now be able to add this in and we can get this one merged too.

**Comment by nwillemse** [comment]
Hi now that #100 is merged, how do I rerun these checks?

**Comment by ryankennedyio** [comment]
:(

Any ideas @femtotrader ??

**Comment by ryankennedyio** [comment]
Well. `nosetests -v` works locally for me. Confusing indeed.

**Comment by mhallsmoore** [comment]
I've just tried re-running the Python 3.4 and 3.5 builds. Python 2.7 seems to work ok.

Here is the error received from the Python 3.4 run:

```
======================================================================
ERROR: Test mac_backtest_tearsheet example
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/mhallsmoore/qstrader/examples/test_examples.py", line 89, in test_mac_backtest_tearsheet
    results = examples.mac_backtest_tearsheet.run(self.config, self.testing, tickers, filename)
  File "/home/travis/build/mhallsmoore/qstrader/examples/mac_backtest_tearsheet.py", line 72, in run
    results = backtest.simulate_trading(testing=testing)
  File "/home/travis/build/mhallsmoore/qstrader/qstrader/trading_session/backtest.py", line 69, in simulate_trading
    results = self.statistics.get_results()
  File "/home/travis/build/mhallsmoore/qstrader/qstrader/statistics/tearsheet.py", line 76, in get_results
    statistics["positions"] = self._get_positions()
  File "/home/travis/build/mhallsmoore/qstrader/qstrader/statistics/tearsheet.py", line 109, in _get_positions
    df['avg_bot'] = df['avg_bot'].apply(x)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/pandas/core/series.py", line 2169, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/src/inference.pyx", line 1059, in pandas.lib.map_infer (pandas/lib.c:62578)
  File "/home/travis/build/mhallsmoore/qstrader/qstrader/statistics/tearsheet.py", line 100, in x
    return PriceParser.display(p)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 161, in __call__
    (self.name, str_signature(types)))
nose.proxy.NotImplementedError: Could not find signature for display: <int64>
```

Is this related to our integer types issue? It's coming up in the multipledispatch code.

**Comment by ryankennedyio** [comment]
Yep, something to do with that @mhallsmoore.

Not sure why it works locally for me with python3. Just pulled @nwillemse's branch to check things out. If I could make it fail locally that would be helpful.

**Comment by ryankennedyio** [comment]
Got it. int64 is a numpy thing. Would explain why multipledispatch doesn't like it. Unsure why environment is making this an int64 though on travis and locally it's fine.


Making a separate PR now which should solve.

**Comment by mhallsmoore** [comment]
Ok, I've merged in @ryankennedyio's fix and am just running the builds again for this PR. Python 2.7 and 3.4 work, just waiting on 3.5...

**Comment by mhallsmoore** [comment]
All builds now pass. Although coverage has decreased somewhat, so in the future we'll need to get it back to 90% again with some additional tests.

Happy to merge now though. This is a great feature! Thanks to everyone for putting in the effort to get it into the codebase, and for @nwillemse for creating it in the first place.

**Pull request merged**
