### PR TITLE
Increase test coverage

### PR DESCRIPTION
**Pull request by ryankennedyio**

### CODE REVIEW

**Comment by ryankennedyio** [comment]
I'm going to be pushing a stack of changes up to this branch, so might not be worth merging until coverage is back into the 90%'s

**Comment by ryankennedyio** [comment]
Ahhhhhh nooooooo, precision errors with the sharpe of monthly liquidation backtest in different versions of python... Any ideas @mhallsmoore ?

**Comment by mhallsmoore** [comment]
This may be due to an error I just fixed, regarding how prices were imported out-of-order in a pandas DataFrame.

I could try merging this in and seeing if I can fix the problem - or should I wait until you've written more tests?

**Comment by ryankennedyio** [comment]
@mhallsmoore I think just merge it in. I will write more tests over the top of https://github.com/mhallsmoore/qstrader/pull/177 once that has been merged into master.

I didn't want to go too far ahead with a failing CI build.

**Comment by mhallsmoore** [comment]
Ryan,

Rather than mucking around with rebasing from the current master, I've added your code in manually to another pull request, so I'll close this one.

Thanks for providing the unit tests for the rebalance code though!

Interestingly enough my branch was still failing in the same way this was (the precision issues between 2.7.x and 3.x.x). It turned out that the error was due to my use of PriceParser in the rebalance class. I've fixed it now (in the other Pull Request) and results are now consistent across both.

Mike.

**Pull request closed without merging**
