### PR TITLE
int/long fix

### LINKED ISSUE #95: Running of buy and hold example strategy generates NotImplementedError: Could not find signature for display: <long>
After setting up QSTrader using the instructions in the readme file, I attempted to run the example buy_and_hold_backtest.py. This generated the error:

```

Traceback (most recent call last):
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeEngine\Lib\site-packages\qstrader\examples\buy_and_hold_backtest.py", line 85, in <module>
    main()
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeEngine\Lib\site-packages\qstrader\examples\buy_and_hold_backtest.py", line 81, in main
    run(config, testing, tickers, filename)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeEngine\Lib\site-packages\qstrader\examples\buy_and_hold_backtest.py", line 65, in run
    results = backtest.simulate_trading(testing=testing)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\qstrader\trading_session\backtest.py", line 68, in simulate_trading
    self._run_backtest()
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\qstrader\trading_session\backtest.py", line 54, in _run_backtest
    self.statistics.update(event.time, self.portfolio_handler)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\qstrader\statistics\simple.py", line 50, in update
    current_equity = PriceParser.display(portfolio_handler.portfolio.equity)
  File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeengine\lib\site-packages\multipledispatch\dispatcher.py", line 161, in __call__
    (self.name, str_signature(types)))
NotImplementedError: Could not find signature for display: <long>
```

I added the below code to the price_parser.py file and the backtest worked. However, the results were not correct; I suspect it is due to my introduction of the below code.

```
    @staticmethod
    @dispatch(long)
    def display(x):
        return round(x / PriceParser.PRICE_MULTIPLIER, 2)
```

What would the correct solution to the original problem be? The platform is Windows+Anaconda (Python 2.7)

Thanks.

### PR DESCRIPTION
**Pull request by femtotrader**
Might closes #95

### CODE REVIEW

**Comment by femtotrader** [comment]
Not sure if it will really closes #95 as I wasn't able to reproduce issue but it shouldn't break anything

**Comment by drex91** [comment]
Hi @femtotrader , thanks for looking into this. I ran the same backtest with the updated code and  returned the below error:

`File "C:\Users\Andre\Anaconda3\envs\python27_env_tradeEngine\lib\site-packages\qstrader\statistics\simple.py", line 57, in update
    pct = ((self.equity[-1] - self.equity[-2]) / self.equity[-1]) * 100
ZeroDivisionError: float division by zero`

I have since reverted back and added:

` @staticmethod
    @dispatch(long)
    def display(x):  # flake8: noqa
        return round(x / PriceParser.PRICE_MULTIPLIER, 2)`

This now resolved the original issue. The second issue I mentioned was due the initial investment amount being less than the default 100 shares and default 1USD commission

I am using Python 2.7.12 :: Continuum Analytics, Inc., Windows 10 64-bit

**Comment by femtotrader** [comment]
long doesn't exist with Python 3

so

```python
try:
    long
except NameError:
    long = int
```

could help for Python 3 support

**Comment by mhallsmoore** [comment]
@femtotrader - Perhaps we should we add in your fix:

```
try:
    long
except NameError:
    long = int
```

And then merge?

**Comment by femtotrader** [comment]
I don't think we should merge this for now as I haven't been able to reproduce error on my side and with Continuous Integration.
Maybe you or @ryankennedyio have been able to reproduce it ?

An other idea could be to setup an other CI environment (Windows specific) like AppVeyor
https://github.com/mhallsmoore/qstrader/issues/108

**Comment by ryankennedyio** [comment]
@femtotrader sorry, don't have a Windows computer. 

I do have a Windows VM on an old macbook air, I can probably spend a few hours trying to set qstrader up on that?

**Comment by femtotrader** [comment]
good idea because I don't think it's a great to merge a fix if we haven't been able to reproduce this issue

**Comment by ryankennedyio** [comment]
Sorry folks. Haven't been able to set up a Windows version of this very successfully. Mostly due to windows being a general pain. I can't sink much personal time into windows compatibility to be honest.

**Pull request merged**
