### PR TITLE
Improve gen CLI

### PR DESCRIPTION
**Pull request by femtotrader**
Closes https://github.com/mhallsmoore/qstrader/issues/37

### CODE REVIEW

**Comment by femtotrader** [comment]
Here is script usage:

```
$ python qstrader/scripts/generate_simulated_prices.py --help
Usage: generate_simulated_prices.py [OPTIONS]

Options:
  --outdir TEXT         Ouput directory (CSV_DATA_DIR)
  --ticker TEXT         Equity ticker symbol (GOOG, SP500TR...)
  --init_price INTEGER  Ticker
  --seed INTEGER        Seed (Fix the randomness by default but use a negative
                        value for true randomness)
  --s0 FLOAT            s0
  --spread FLOAT        spread
  --mu_dt INTEGER       mu_dt (Milliseconds)
  --sigma_dt INTEGER    sigma_dt (Milliseconds)
  --year INTEGER        Year
  --month INTEGER       Month
  --help                Show this message and exit.
```

**Comment by mhallsmoore** [comment]
This is useful - thanks @femtotrader!

Before I add the PR I'd like to have a specific version for the "click" library in the requirements file. At the moment there is no version information. If you add one, I'll merge it in.

**Comment by femtotrader** [comment]
You might enable Travis on your side also to ensure that's ok or not.

**Comment by femtotrader** [comment]
On my side it's ok https://travis-ci.org/qstraders/qstrader
https://travis-ci.org/qstraders/qstrader/builds/139751666

Did you enable Travis ?
Because that's important now I suggest to only merge when CI is ok

Thanks for merging

**Pull request merged**
