### PR TITLE
Ignore hidden files created by Textmate (a editor for Mac)

### PR DESCRIPTION
**Pull request by jacohn16**
Purely for selfish reasons   :P

...and possibly for the sake of others that use Textmate as well.

### CODE REVIEW

**Comment by femtotrader** [comment]
It shouldn't be merged... because it's not only changing `.gitignore`
That's probably an issue on your side.
I think you need to rebase

**Comment by mhallsmoore** [comment]
It contains an example of running a strategy via Quandl data, using a Quandl PriceHandler. @jacohn16 - thanks for adding this! I'll need to sit down for a bit and merge in the changes manually, as the master has changed somewhat. Rebasing is probably a good idea, as suggested by @femtotrader.

**Comment by jacohn16** [comment]
I'm confused why this is happening.  So first I made the change in .gitignore and pushed the commit from my local repo to Github.  Then I opened the PR.  Then I tried to commit the 2nd change (quandl price handler implementation), but I wanted to commit *only* to my forked repo.  I didn't want to submit a PR for this yet, because I wanted to further develop the futures pricing....and request PR once its all ready.   

But where did I do wrong here?  When you say I should rebase.  How exactly should the rebase be done?  (sorry about the newbie questions)

This is the bit of history on my local master:

* 0e3c6f7 - jacohn1@gmail.com, Thu Jun 23 03:48:37 2016 -0700 : Initial implementation of a quandl price handler
* 5009a2b - jacohn1@gmail.com, Thu Jun 23 03:19:03 2016 -0700 : Ignore hidden files created by Textmate (a editor for Mac)
*   5b4e62d - noreply@github.com, Mon Jun 13 10:02:36 2016 +0100 : Merge pull request #29 from ryankennedyio/compliance
|\  
| * 79276c4 - hello@ryankennedy.io, Mon Jun 13 10:56:28 2016 +0930 : Revert MAC strategy instrument to AAPL
| * 05310e3 - hello@ryankennedy.io, Wed Jun 1 21:06:14 2016 +0930 : Revert ticker used in example MAC backtest
| * 39c9c6a - hello@ryankennedy.io, Wed Jun 1 20:46:34 2016 +0930 : Add TestCompliance to the example backtests
| * 58e3177 - hello@ryankennedy.io, Wed Jun 1 20:36:04 2016 +0930 : Compliance module now keeps a CSV trade log of any trades that are executed
| * 71229de - hello@ryankennedy.io, Wed Jun 1 19:03:22 2016 +0930 : Added compliance directory, started a basic compliance module, use it as an optional parameter in the IBSimul
| *   2fa9d9f - hello@ryankennedy.io, Wed Jun 1 18:39:24 2016 +0930 : Merge remote-tracking branch 'upstream/master'
| |\

**Comment by femtotrader** [comment]
You should make a local copy of your code and remove your commits.

```
$ git reset --soft HEAD~2
$ git push -f
```

CAUTION ! DO THIS AT YOUR OWN RISK!!!

**Comment by femtotrader** [comment]
I suggest to always work in a branch for new features (not master)
even in your repository.

**Pull request closed without merging**
