### PR TITLE
Save results

### LINKED ISSUE #82: Serialize results
Hello,

it will be a good idea to store results into file.
So that we will be able to display again equity / drawdown plots...
and also get a DataFrame showing when trades occur in an interactive way (IPython...) after running a backtest.

Serialization can be done using Pickle.

An other option could be to store results to HDF5 files.

Maybe we should consider to build something on top of PyPET (in order to avoid reinventing a "squared wheel") https://pypet.readthedocs.io/en/latest/manual/introduction.html#getting-started

Kind regards

### PR DESCRIPTION
**Pull request by femtotrader**
Close #82

This PR envolved some changes into Statistics method such as update
to avoid to serialize unecessary stuff.

Statistics can be easily retrieved using:

```python
from qstrader.statistics import load
stats = load("output_directory/statistics_yyyy-mm-dd_HHMMSS.pkl")
```

Bokeh TimeSeries plot may be improved according 
https://github.com/bokeh/bokeh/issues/4747

Other interactive plotting libraries can also if we can't fix this.

### CODE REVIEW

**Comment by femtotrader** [comment]
We can also use mpld3 to plot an interactive equity time series

http://mpld3.github.io/

```python
import mpld3
mpld3.enable_notebook()
ts.plot()
```

**Comment by femtotrader** [comment]
Nice zoom feature!
capture d ecran 2016-07-05 a 07 51 06
capture d ecran 2016-07-05 a 07 51 18

**Comment by mhallsmoore** [comment]
I think we should agree in the future as to whether to merge PRs if test coverage has decreased. Given the slight decrease I'm not particularly concerned here, but if we introduce major new changes and test coverage decreases significantly, I don't believe we should merge the PRs.

Thoughts?

**Comment by femtotrader** [comment]
I agree! Testing new features is as much important as adding new features.

**Comment by femtotrader** [comment]
Bokeh 0.12 fixes x-axis issue with time series so we can have this kind of interactive plot in Jupyter notebook.

capture d ecran 2016-07-07 a 17 49 33

capture d ecran 2016-07-07 a 17 49 49

**Comment by mhallsmoore** [comment]
Just to check before merging, what dependencies are we adding here? Bokeh and mpld3?

**Comment by femtotrader** [comment]
Bokeh and mpld3 is only used in Jupyter Notebook. It's not dependencies that's just optional for plotting.

**Comment by mhallsmoore** [comment]
Cool - just merged.

**Comment by femtotrader** [comment]
Thanks

**Pull request merged**
